# -*- coding: utf-8 -*-
"""
Created on Wed Nov 26 12:32:30 2025

@author: abaeim1
"""

""" Script generated by pyDatView - The script will likely need to be adapted. """
import matplotlib.pyplot as plt
import numpy as np
import pydatview.io as weio

# --- Script parameters
filename = 'C:/Simulations/outputs/parametric/case_1.out'

# --- Open and convert files to DataFrames
dfs = {}
dfs[0] = weio.read(filename).toDataFrame()

# --- Plot
lw = 1.5 
stys = ['-', '--', '-.', ':'] * 100
tabNames = list(dfs.keys())
fig,ax = plt.subplots(1, 1, sharex=True, figsize=(6.4,4.8))
fig.subplots_adjust(left=0.12, right=0.95, top=0.95, bottom=0.11, hspace=0.20, wspace=0.20)
df = dfs[tabNames[0]]


# ax.plot(df['Time_[s]'], df['TwHt1ALxt_[m/s^2]'], ls=stys[0], lw=lw, label='TwHt1ALxt [m/s^2]')
# ax.plot(df['Time_[s]'], df['TwHt2ALxt_[m/s^2]'], ls=stys[1], lw=lw, label='TwHt2ALxt [m/s^2]')
# ax.plot(df['Time_[s]'], df['TwHt3ALxt_[m/s^2]'], ls=stys[2], lw=lw, label='TwHt3ALxt [m/s^2]')
# ax.plot(df['Time_[s]'], df['TwHt4ALxt_[m/s^2]'], ls=stys[3], lw=lw, label='TwHt4ALxt [m/s^2]')
# ax.plot(df['Time_[s]'], df['TwHt5ALxt_[m/s^2]'], ls=stys[4], lw=lw, label='TwHt5ALxt [m/s^2]')
# ax.plot(df['Time_[s]'], df['TwHt6ALxt_[m/s^2]'], ls=stys[5], lw=lw, label='TwHt6ALxt [m/s^2]')
# ax.plot(df['Time_[s]'], df['TwHt7ALxt_[m/s^2]'], ls=stys[6], lw=lw, label='TwHt7ALxt [m/s^2]')
# ax.plot(df['Time_[s]'], df['TwHt8ALxt_[m/s^2]'], ls=stys[7], lw=lw, label='TwHt8ALxt [m/s^2]')
# ax.plot(df['Time_[s]'], df['TwHt9ALxt_[m/s^2]'], ls=stys[8], lw=lw, label='TwHt9ALxt [m/s^2]')
# ax.set_xlabel('Time [s]')
# ax.legend(loc='upper right')
# ax.grid()
# plt.show()